return {
  ["workshop-100010002"]={
    configuration_options={
      amount_of_numbers="default",
      display_mode="waving",
      dmg_only="on",
      show_decimal_points="no" 
    },
    enabled=true 
  },
  ["workshop-100010023"]={
    configuration_options={
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-100010024"]={
    configuration_options={
      Craft="Easy",
      Destroyable="yees",
      FoodSpoilage=0,
      Language="En",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-100010027"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-100010058"]={
    configuration_options={ DFV_Language="CN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-100010062"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=true,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-2199027653598512025"]={ configuration_options={ uses=10000000000 }, enabled=true } 
}